//
// Copyright (C) 2020 IOTech Ltd
//
// SPDX-License-Identifier: Apache-2.0

package dtos

import (
	v2 "github.com/edgexfoundry/go-mod-core-contracts/v2"
	"github.com/edgexfoundry/go-mod-core-contracts/v2/dtos/common"
	"github.com/edgexfoundry/go-mod-core-contracts/v2/models"
)

const (
	ValueTypeBinary  = "Binary"
	ValueTypeFloat32 = "Float32"
	ValueTypeFloat64 = "Float64"
	ValueTypeUint8   = "Uint8"
)

// BaseReading defines the content of a reading object (usually generated by a device service)
// which can contain a SimpleReading or a BinaryReading (but not both).
// This object and its properties correspond to the BaseReading object in the APIv2 specification:
// https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/BaseReading
type BaseReading struct {
	common.Versionable `json:",inline"`
	Id                 string   `json:"id"`
	Created            int64    `json:"created"`
	Origin             int64    `json:"origin" validate:"required"`
	DeviceName         string   `json:"deviceName" validate:"required"`
	Name               string   `json:"name" validate:"required"`
	Labels             []string `json:"labels,omitempty"`
	ValueType          string   `json:"valueType" validate:"required"`
	BinaryReading      `json:",inline" validate:"-"`
	SimpleReading      `json:",inline" validate:"-"`
}

// BinaryReading defines the content of the binary form of a reading object (usually generated by a device service)
// This object and its properties correspond to the BinaryReading object in the APIv2 specification:
// https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/BinaryReading
type BinaryReading struct {
	BinaryValue []byte `json:"binaryValue" validate:"gt=0,dive,required"`
	MediaType   string `json:"mediaType" validate:"required"`
}

// SimpleReading defines the content of the simple reading object (usually generated by a device service)
// which can contain simple non-binary data types.
// This object and its properties correspond to the SimpleReading object in the APIv2 specification:
// https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/SimpleReading
type SimpleReading struct {
	Value         string `json:"value" validate:"required"`
	FloatEncoding string `json:"floatEncoding,omitempty"`
}

// Validate satisfies the Validator interface
func (b BaseReading) Validate() error {
	if b.ValueType == ValueTypeBinary {
		// validate the inner BinaryReading struct
		binaryReading := b.BinaryReading
		if err := v2.Validate(binaryReading); err != nil {
			return err
		}
	} else {
		// validate the inner SimpleReading struct
		simpleReading := b.SimpleReading
		// check if FloatEncoding has value when ValueType is Float32 or Float64
		if b.ValueType == ValueTypeFloat32 || b.ValueType == ValueTypeFloat64 {
			if simpleReading.FloatEncoding == "" {
				return v2.NewErrContractInvalid("FloatEncoding field is required when valueType is Float32 or Float64.")
			}
		}
		if err := v2.Validate(simpleReading); err != nil {
			return err
		}
	}

	return nil
}

// Convert Reading DTO to Reading model
func ToReadingModel(r BaseReading, device string) models.Reading {
	var readingModel models.Reading
	br := models.BaseReading{
		Origin:     r.Origin,
		DeviceName: r.DeviceName,
		Name:       r.Name,
		Labels:     r.Labels,
		ValueType:  r.ValueType,
	}
	if r.ValueType != "" {
		readingModel = models.SimpleReading{
			BaseReading: br,
			Value:       r.Value,
		}
	} else {
		readingModel = models.BinaryReading{
			BaseReading: br,
			BinaryValue: r.BinaryValue,
			MediaType:   r.MediaType,
		}
	}
	return readingModel
}

func FromReadingModelToDTO(reading models.Reading) BaseReading {
	var baseReading BaseReading
	switch r := reading.(type) {
	case models.BinaryReading:
		baseReading = BaseReading{
			Versionable:   common.Versionable{ApiVersion: v2.ApiVersion},
			Id:            r.Id,
			Created:       r.Created,
			Origin:        r.Origin,
			DeviceName:    r.DeviceName,
			Name:          r.Name,
			Labels:        r.Labels,
			ValueType:     r.ValueType,
			BinaryReading: BinaryReading{BinaryValue: r.BinaryValue, MediaType: r.MediaType},
		}
	case models.SimpleReading:
		baseReading = BaseReading{
			Versionable:   common.Versionable{ApiVersion: v2.ApiVersion},
			Id:            r.Id,
			Created:       r.Created,
			Origin:        r.Origin,
			DeviceName:    r.DeviceName,
			Name:          r.Name,
			Labels:        r.Labels,
			ValueType:     r.ValueType,
			SimpleReading: SimpleReading{Value: r.Value, FloatEncoding: r.FloatEncoding},
		}
	}

	return baseReading
}
